### ISSUE TITLE
Server disconnected without sending a response.

### ISSUE THREAD

**Issue by CaffuChin0** [Reversedeer/nonebot_plugin_dog#2]
查找了报错Issues#1

httpx版本0.23.3

报错信息：(也没有error)
![1](https://user-images.githubusercontent.com/47897127/222371431-3b269729-1c22-4e86-a8de-1cd793966626.png)

系统：Ubuntu

版本：0.2.3
![version](https://user-images.githubusercontent.com/47897127/222374528-0339d0f6-126b-436a-92cd-6aea39f6f011.png)

python3.10

**Comment by Reversedeer** [comment]
有可能是其他插件消息阻断了，调整一下各插件的优先级，应该不是本插件的问题

**Comment by CaffuChin0** [comment]
> 有可能是其他插件消息阻断了，调整一下各插件的优先级，应该不是本插件的问题

将优先级调至1（最高）也一样出现Server disconnected without sending a response.

**Comment by Reversedeer** [comment]
你的日志里里没出现Server disconnected without sending a response.
我没有办法复现你的问题

**Comment by Reversedeer** [comment]
已更新v0.2.5

**Comment by Reversedeer** [comment]
> disconnected without sending a resp

应该是你的网络问题啊，我这边正常
