### ISSUE TITLE
报错：SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Agnes4m** [Reversedeer/nonebot_plugin_dog#3]
版本pypi0..2.6,ubuntu20.04,python3.9,nonebot2.0.0rc3
除了一言，其他三个都返回
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.juncikeji.xyz'. (_ssl.c:1129)`

**Comment by Reversedeer** [comment]
是网站SSL证书的问题，晚上发新版

**Comment by Reversedeer** [comment]
已修复
pypi 已发新版v0.2.7
