### ISSUE TITLE
插件版本不对啊 

### ISSUE THREAD

**Issue by ATTomatoo** [Reversedeer/nonebot_plugin_dog#5]
github主页上还是停留在0.2.6，但实际为0.2.7为最新

（我群里群友由于是在太能舔了，说是文章总是已经开始重复了，能否加点库存）

**Comment by Reversedeer** [comment]
1.github上可能不是最新，以pypi上版本为主
2.在下个版本可以考虑新增“舔狗日记”的更多获取方式

**Comment by Reversedeer** [comment]
您在使用v0.2.6版本时没有报错吗

**Comment by Satori3rdEye** [comment]
> 1.github上可能不是最新，以pypi上版本为主 2.在下个版本可以考虑新增“舔狗日记”的更多获取方式

还有笑话还是有“\n”显示

**Comment by Reversedeer** [comment]
1.针对本issue，V 0.2.7.1 dev版本已经进行了更新，github没发此版本
2.针对“讲个笑话”出现"\n"的bug你可以开一个新的issue。

**Comment by Reversedeer** [comment]
https://github.com/Reversedeer/nonebot_plugin_dog/tree/dev
查看最新的dev

> github主页上还是停在0.2.6，但实际为0.2.7为最新
> 
> （我群里群友是因为太能舔了，说是文章总已经开始重新恢复了，能不能加点库存）

**Comment by ATTomatoo** [comment]
好的，辛苦作者大大了
